#!/bin/sh
set -e
if [ ! -f /usr/local/lib/python3.6/dist-packages/openpyn/credentials ]; then
    echo $NORDVPN_USERNAME >> /usr/local/lib/python3.6/dist-packages/openpyn/credentials
    echo $NORDVPN_PASSWORD >> /usr/local/lib/python3.6/dist-packages/openpyn/credentials
    chmod 600 /usr/local/lib/python3.6/dist-packages/openpyn/credentials
fi

openpyn $COUNTRY $ARG
